import React, { Component } from 'react';
import Footer from '../components/Footer/Footer';
import PagerBannerForRestaurantReservation from '../components/PageBanner/PagerBannerForRestaurantReservation';

export default class Refund extends Component {
	render() {
		return (
			<>
				<PagerBannerForRestaurantReservation
					minusTop={true}
					title="Privacy Policy"
					background={
						'https://img.freepik.com/premium-photo/cabinet-tv-white-plaster-wall-living-room-with-armchair-minimal-design-3d-rendering_41470-3003.jpg?w=2000'
					}
				/>
				<div className="policy py-5">
					<div className="container">
						<div className="row">
							<div className="col-xl-10 text-light mx-auto">
								<h3 className="display-5 mb-2">Privacy Policy</h3>
								<p className="mb-0 fs-6 lh-base mb-4">
									This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
									information when You use the Service and tells You about Your privacy rights and how the law protects You. We use
									Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use
									of information in accordance with this Privacy Policy.
								</p>
								<div className="block-widget mb-4">
									<h5 className="mb-2">INTERPRETATION AND DEFINITIONS</h5>
									<p className="mb-1">
										<strong>Interpretation</strong>
									</p>
									<p>
										The words of which the initial letter is capitalized have meanings defined under the following conditions. The
										following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
									</p>
									<p className="mb-1">
										<strong>For the purposes of this Privacy Policy:</strong>
									</p>
									<ul>
										<li>
											Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Insignia
											Hotels & Resorts, 156 Mudafa Purbo Para, Tongi, Gazipur 1711, Bangladesh.
										</li>
										<li>
											Cookies are small files that are placed on Your computer, mobile device or any other device by a website,
											containing the details of Your browsing history on that website among its many uses.
										</li>
										<li>Country refers to: Bangladesh</li>
										<li>
											Device means any device that can access the Service such as a computer, a cell phone or a digital tablet.
										</li>
										<li>Personal Data is any information that relates to an identified or identifiable individual.</li>
										<li>Service refers to the Website.</li>
										<li>Service Provider means any natural or legal person who processes the data on behalf of the Company.</li>
										<li>
											Usage Data refers to data collected automatically, either generated by the use of the Service or from the
											Service infrastructure itself (for example, the duration of a page visit).
										</li>
										<li>Website refers to Insignia, accessible from https://www.insignia-resorts.com</li>
										<li>
											You mean the individual accessing or using the Service, or the company, or other legal entity on behalf of
											which such individual is accessing or using the Service, as applicable.
										</li>
									</ul>
								</div>
								<div className="block-widget mb-4">
									<h5 className="mb-2">COLLECTING AND USING YOUR PERSONAL DATA</h5>
									<p className="mb-1">
										<strong>Types of Data Collected</strong> <br />
										<strong>PERSONAL DATA</strong>
									</p>
									<p>
										While using Our Service, We may ask You to provide Us with certain personally identifiable information that
										can be used to contact or identify You. Personally identifiable information may include, but is not limited
										to:
									</p>
									<ul>
										<li>Email address</li>
										<li>First name and last name</li>
										<li>Phone number</li>
									</ul>
								</div>
								<div className="block-widget mb-4">
									<h5 className="mb-2">Use of Your Personal Data</h5>
									<p className="mb-1">
										<strong>The Company may use Personal Data for the following purposes:</strong>
									</p>
									<p>To provide and maintain our Service: including to monitor the usage of our Service.</p>
									<p>
										For the performance of a contract: the development, compliance and undertaking of the purchase contract for
										the products, items or services You have purchased or of any other contract with Us through the Service.
									</p>
									<p>
										To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic
										communication, such as a mobile application's push notifications regarding updates or informative
										communications related to the functionalities, products or contracted services, including the security
										updates, when necessary or reasonable for their implementation.
									</p>
									<p>
										To provide You: with news, special offers and general information about other goods, services and events which
										we offer that are similar to those that you have already purchased or enquired about unless You have opted not
										to receive such information.
									</p>
									<p>To manage Your requests: To attend and manage Your requests to Us.</p>
									<p>
										For business transfers: We may use Your information to evaluate or conduct a merger, divestiture,
										restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as
										a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by
										Us about our Service users is among the assets transferred.
									</p>
									<p>
										For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage
										trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service,
										products, services, marketing and your experience. We may share Your personal information in the following
										situations:
									</p>
									<p>
										With Service Providers: We may share Your personal information with Service Providers to monitor and analyze
										the use of our Service, to contact You.
									</p>
									<p>
										For business transfers: We may share or transfer Your personal information in connection with, or during
										negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our
										business to another company.
									</p>
									<p>
										With Affiliates: We may share Your information with Our affiliates, in which case we will require those
										affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries,
										joint venture partners or other companies that We control or that are under common control with Us.
									</p>
									<p>
										With business partners: We may share Your information with Our business partners to offer You certain
										products, services or promotions.
									</p>
									<p>
										With other users: when You share personal information or otherwise interact in the public areas with other
										users, such information may be viewed by all users and may be publicly distributed outside.
									</p>
									<p>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</p>
								</div>
								<div className="block-widget mb-4">
									<p className="mb-1">
										<strong>Retention of Your Personal Data</strong>
									</p>
									<p>
										The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this
										Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal
										obligations (for example, if we are required to retain your data to comply with applicable laws), resolve
										disputes, and enforce our legal agreements and policies. The Company will also retain Usage Data for internal
										analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is
										used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to
										retain this data for longer time periods.
									</p>
								</div>
								<div className="block-widget mb-4">
									<p className="mb-1">
										<strong>Transfer of Your Personal Data</strong>
									</p>
									<p>
										Your information, including Personal Data, is processed at the Company's operating offices and in any other
										places where the parties involved in the processing are located. It means that this information may be
										transferred to — and maintained on — computers located outside of Your state, province, country or other
										governmental jurisdiction where the data protection laws may differ from Your jurisdiction.
									</p>
									<p>
										Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement
										to that transfer. The Company will take all steps reasonably necessary to ensure that Your data is treated
										securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to
										an organization or a country unless there are adequate controls in place including the security of Your data
										and other personal information.
									</p>
								</div>
								<div className="block-widget mb-4">
									<p className="mb-1">
										<strong>DISCLOSURE OF YOUR PERSONAL DATA BUSINESS TRANSACTIONS</strong>
									</p>
									<p>
										If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We
										will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy
										Policy.
									</p>
								</div>
								<div className="block-widget mb-4">
									<p className="mb-1">
										<strong>LAW ENFORCEMENT</strong>
									</p>
									<p>
										Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so
										by law or in response to valid requests by public authorities (e.g. a court or a government agency).
									</p>
								</div>
								<div className="block-widget mb-4">
									<h5 className="mb-2">OTHER LEGAL REQUIREMENTS</h5>
									<p className="mb-1">
										<strong>
											The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
										</strong>
									</p>
									<p>
										Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so
										by law or in response to valid requests by public authorities (e.g. a court or a government agency).
									</p>
									<ul>
										<li>Comply with a legal obligation</li>
										<li>Protect and defend the rights or property of the Company</li>
										<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
										<li>Protect the personal safety of Users of the Service or the public</li>
										<li>Protect against legal liability</li>
									</ul>
								</div>
								<div className="block-widget mb-4">
									<h5 className="mb-2">SECURITY OF YOUR PERSONAL DATA</h5>
									<p>
										The security of Your Personal Data is important to Us, but remember that no method of transmission over the
										Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means
										to protect Your Personal Data, We cannot guarantee its absolute security.
									</p>
								</div>
								<div className="block-widget mb-4">
									<h5 className="mb-2">DETAILED INFORMATION ON THE PROCESSING OF YOUR PERSONAL DATA</h5>
									<p>
										The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store,
										use, process and transfer information about Your activity on Our Service in accordance with their Privacy
										Policies.
									</p>
								</div>
								<div className="block-widget mb-4">
									<h5 className="mb-2">USAGE, PERFORMANCE AND MISCELLANEOUS</h5>
									<p>We may use third-party Service Providers to provide better improvement of our Service.</p>
								</div>
								<div className="block-widget mb-4">
									<h5 className="mb-2">CHILDREN'S PRIVACY</h5>
									<p>
										Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
										information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child
										has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data
										from anyone under the age of 13 without verification of parental consent, We take steps to remove that
										information from Our servers. If We need to rely on consent as a legal basis for processing Your information
										and Your country requires consent from a parent, We may require Your parent's consent before We collect and
										use that information.
									</p>
								</div>
								<div className="block-widget mb-4">
									<h5 className="mb-2">LINKS TO OTHER WEBSITES</h5>
									<p>
										Our Service may contain links to other websites that are not operated by Us. If You click on a third party
										link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of
										every site You visit. We have no control over and assume no responsibility for the content, privacy policies
										or practices of any third party sites or services.
									</p>
								</div>
								<div className="block-widget mb-4">
									<h5 className="mb-2">CHANGES TO THIS PRIVACY POLICY</h5>
									<p>
										We may update Our Privacy Policy from time to time. You are advised to review this Privacy Policy periodically
										for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
									</p>
								</div>
								<div className="block-widget mb-4">
									<h5 className="mb-2">CONTACT US</h5>
									<p>If you have any questions about this Privacy Policy, You can contact us:</p>
									<ul>
										<li>By email: info@insignia-resorts.net</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
				<Footer />
			</>
		);
	}
}
